---
- include: setup.yml

- name: Install Filebeat
  package:
    name: filebeat
    state: latest

- include: config.yml
  when: filebeat_create_config | bool

- name: Ensure Filebeat is started and enabled at boot
  service:
    name: filebeat
    state: started
    enabled: true
